name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t youngethan4/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push youngethan4/auth
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{secrets.DOCTL_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save k8s-ticketing
      - run: kubectl rollout restart deployment auth-depl
