name: tests-payments

# event
on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
        env:
          super_secret: ${{ secrets.STRIPE_KEY }}
